language: shell
os: linux
dist: bionic
addons:
  apt:
    update: true
    packages: [bash, mksh, yash, zsh, shellcheck]
jobs:
  include:
    - os: linux
      dist: bionic
      env: COVERAGE=1 SHELLCHECK=1
      services: docker
    - os: osx
      osx_image: xcode11.3
    - os: windows
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - curl -fsSL https://git.io/shellspec | sh -s master -y
script:
  - ./test.sh
  - if [ "$SHELLCHECK" ]; then make check; fi
  - if [ "$COVERAGE" ]; then make coveralls; fi
