language: shell
os: linux
dist: bionic
addons:
  apt:
    update: true
    packages: [bash, mksh, yash, zsh, shellcheck]
  homebrew:
    update: true
    packages: [shellcheck]
jobs:
  include:
    - os: linux
      dist: bionic
      env: COVERAGE=1
      services: docker
    - os: osx
      osx_image: xcode11.3
before_install:
  - curl -fsSL https://git.io/shellspec | sh -s master -y
script:
  - make test
  - make check
  - if [ "$COVERAGE" ]; then make coveralls; fi
